//login
export const LOGIN_PROCESS = "LOGIN_PROCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

// registration
export const REGISTER_PROCESS = "REGISTER_PROCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// main page
export const FETCH_ALL_POSTS_PROCESS = "FETCH_ALL_POSTS_PROCESS";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_ALL_POSTS_FAIL = "FETCH_ALL_POSTS_FAIL";

// post page
export const FETCH_POST_PROCESS = "FETCH_POST_PROCESS";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";

export const FETCH_LIKE_FROM_SOCKET = "FETCH_LIKE_FROM_SOCKET";

// create the new post
export const CREATE_POST_PROCESS = "CREATE_POST_PROCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

// user profile
export const FETCH_USER_PROFILE_PROCESS = "FETCH_USER_PROFILE_PROCESS";
export const FETCH_USER_PROFILE_FAIL = "FETCH_USER_PROFILE_FAIL";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";

// edit user profile
export const EDIT_USER_PROFILE_PROCESS = "EDIT_USER_PROFILE_PROCESS";
export const EDIT_USER_PROFILE_FAIL = "EDIT_USER_PROFILE_FAIL";
export const EDIT_USER_PROFILE_SUCCESS = "EDIT_USER_PROFILE_SUCCESS";

// likes, dislikes of posts
export const EDIT_LIKE_OF_POST_SUCCESS = "EDIT_LIKE_OF_POST_SUCCESS";
export const EDIT_DISLIKE_OF_POST_SUCCESS = "EDIT_DISLIKE_OF_POST_SUCCESS";

// create the new event
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";
export const CREATE_EVENT_PROCESS = "CREATE_EVENT_PROCESS";

// all events
export const FETCH_ALL_EVENTS_PROCESS = "FETCH_ALL_EVENTS_PROCESS";
export const FETCH_ALL_EVENTS_SUCCESS = "FETCH_ALL_EVENTS_SUCCESS";
export const FETCH_ALL_EVENTS_FAIL = "FETCH_ALL_EVENTS_FAIL";

// delete the event
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

// subscribe
export const EDIT_SUBSCRIBE_TO_EVENT = "EDIT_SUBSCRIBE_TO_EVENT";
export const EDIT_UNSUBSCRIBE_TO_EVENT = "EDIT_UNSUBSCRIBE_TO_EVENT";
export const EDIT_SUBSCRIBE_TO_ALL_EVENTS = "EDIT_SUBSCRIBE_TO_ALL_EVENTS";
export const EDIT_UNSUBSCRIBE_TO_ALL_EVENTS = "EDIT_UNSUBSCRIBE_TO_ALL_EVENTS";

// comments
export const FETCH_COMMENTS_OF_POST_PROCESS = "FETCH_COMMENTS_OF_POST_PROCESS";
export const FETCH_COMMENTS_OF_POST_SUCCESS = "FETCH_COMMENTS_OF_POST_SUCCESS";
export const FETCH_COMMENTS_OF_POST_FAIL = "FETCH_COMMENTS_OF_POST_FAIL";
 